### ISSUE TITLE
Improve adding tracker process

### ISSUE THREAD

**Issue by ElpadoCan** [SchmollerLab/Cell_ACDC#150]
Improve adding tracker process:

- [x] Read keyword arguments of both the `__init__` and `track` methods of the `tracker` class 
- [x] Prompt user with the dialogue to initialize parameters as it is done for the segmentation models
- [x] Automatically read which trackers have the `track_frame` method and add them to the real-time trackers in the GUI
