### ISSUE TITLE
Add second step to Cell-ACDC tracker to track based on distance

### ISSUE THREAD

**Issue by ElpadoCan** [SchmollerLab/Cell_ACDC#454]
### Description:

In the second step, track the objects that are not tracked with IoU using the distance between centroids. 

To do:

- [x] Visual warning on those cells that were tracked with second step --> line connecting yellow lost object to cell tracked with second step 
- [x] Use cost matrix on distance and linear sum assignment problem
- [x] Use a maximum distance threshold customisable by the user
