### ISSUE TITLE
Improvement on how to handle IDs of first frame when tracking in the GUI

### ISSUE THREAD

**Issue by ElpadoCan** [SchmollerLab/Cell_ACDC#497]
### Description:

The function `workers.trackingWorker._relabel_first_frame_labels` is quite slow with 4D data. Possible improvements:

- [ ] Ensure that `trackpy` does not change the IDs of the first frame
- [ ] Check if the first frame untracked version is the same of the first frame tracked version --> if yes, no need to call the function
- [x] Change implementation of the function to run with for loops on each frame
